variables:
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"
  MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"

image: maven:3-openjdk-11

cache:
  paths:
    - .m2/repository
    - target

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS compile

test:
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS verify
    - awk -F"," '{ instructions += $4 + $5; covered += $5 } END { print covered, "/", instructions, "instructions covered"; print 100*covered/instructions, "% covered" }' target/site/jacoco/jacoco.csv
    - bash <(curl -Ls https://coverage.codacy.com/get.sh) report
  coverage: '/(\d+\.?\d*) \% covered/'

snapshot:
  stage: deploy
  script:
    - mvn $MAVEN_CLI_OPTS -s ci_settings.xml deploy -DskipTests -ntp -DaltDeploymentRepository=gitlab-maven::default::${CI_SERVER_URL}/api/v4/projects/${CI_PROJECT_ID}/packages/maven
  only:
    - branches
  except:
    - master


release:
  stage: deploy
  script:
    - mvn $MAVEN_CLI_OPTS -s ci_settings.xml clean deploy site -Dchangelist= -DskipTests -ntp -Psources,javadocs -DaltDeploymentRepository=gitlab-maven::default::${CI_SERVER_URL}/api/v4/projects/${CI_PROJECT_ID}/packages/maven
    - mv target/site public
    - mv target/apidocs public
    - mv public/images/favicon.ico public
  artifacts:
    paths:
      - public
  only:
    - tags
